// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetBranchEndpointsEndpoint {
    /**
     * Endpoint URI.
     */
    host?: string;
    /**
     * Endpoint ID.
     */
    id?: string;
    proxyHost?: string;
    /**
     * Deployment region: https://neon.tech/docs/introduction/regions
     */
    regionId?: string;
    /**
     * Access type.
     */
    type?: string;
}

export interface GetBranchEndpointsEndpointArgs {
    /**
     * Endpoint URI.
     */
    host?: pulumi.Input<string>;
    /**
     * Endpoint ID.
     */
    id?: pulumi.Input<string>;
    proxyHost?: pulumi.Input<string>;
    /**
     * Deployment region: https://neon.tech/docs/introduction/regions
     */
    regionId?: pulumi.Input<string>;
    /**
     * Access type.
     */
    type?: pulumi.Input<string>;
}

export interface GetBranchRolesRole {
    /**
     * Role name.
     */
    name?: string;
    protected?: boolean;
}

export interface GetBranchRolesRoleArgs {
    /**
     * Role name.
     */
    name?: pulumi.Input<string>;
    protected?: pulumi.Input<boolean>;
}

export interface ProjectBranch {
    /**
     * The name of the default database provisioned upon creation of new project. It's owned by the default role (`role_name`).
     * If not specified, the default database name will be used.
     */
    databaseName?: pulumi.Input<string>;
    /**
     * Branch ID.
     */
    id?: pulumi.Input<string>;
    /**
     * The name of the default branch provisioned upon creation of new project.
     * If not specified, the default branch name will be used.
     */
    name?: pulumi.Input<string>;
    /**
     * The name of the default role provisioned upon creation of new project.
     * If not specified, the default role name will be used.
     */
    roleName?: pulumi.Input<string>;
}

export interface ProjectDefaultEndpointSettings {
    autoscalingLimitMaxCu?: pulumi.Input<number>;
    autoscalingLimitMinCu?: pulumi.Input<number>;
    /**
     * Endpoint ID.
     */
    id?: pulumi.Input<string>;
    /**
     * Duration of inactivity in seconds after which the compute endpoint is automatically suspended.
     * The value 0 means use the global default.
     * The value -1 means never suspend. The default value is 300 seconds (5 minutes).
     * The maximum value is 604800 seconds (1 week)
     */
    suspendTimeoutSeconds?: pulumi.Input<number>;
}

export interface ProjectMaintenanceWindow {
    /**
     * End time of the maintenance window, in the format of "HH:MM". Uses UTC.
     */
    endTime: pulumi.Input<string>;
    /**
     * Start time of the maintenance window, in the format of "HH:MM". Uses UTC.
     */
    startTime: pulumi.Input<string>;
    /**
     * A list of weekdays when the maintenance window is active. Encoded as ints, where 1 - Monday, and 7 - Sunday.
     */
    weekdays: pulumi.Input<pulumi.Input<number>[]>;
}

export interface ProjectQuota {
    /**
     * The total amount of wall-clock time allowed to be spent by the project's compute endpoints.
     */
    activeTimeSeconds?: pulumi.Input<number>;
    /**
     * The total amount of CPU seconds allowed to be spent by the project's compute endpoints.
     */
    computeTimeSeconds?: pulumi.Input<number>;
    /**
     * Total amount of data transferred from all of a project's branches using the proxy.
     */
    dataTransferBytes?: pulumi.Input<number>;
    /**
     * Limit on the logical size of every project's branch.
     */
    logicalSizeBytes?: pulumi.Input<number>;
    /**
     * Total amount of data written to all of a project's branches.
     */
    writtenDataBytes?: pulumi.Input<number>;
}
