name: nigel-data-neon
runtime:
  name: nodejs
  options:
    packagemanager: bun
    nodeargs: "--import tsx"
description: Pulumi project for Nigel's Neon Postgres database (prod-only)
main: index.ts
packages:
  neon:
    source: pulumi/pulumi/terraform-provider
    version: v0.13.0
    parameters:
      - kislerdm/neon
      - 0.13.0
